flags:
  generic-deriving:
    base-4-9: false
extra-package-dbs: []
packages:
- .
- ../../tct/term-rewriting-ext/
system-ghc: false
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.4
- ansi-terminal-0.8.0.2
- ansi-wl-pprint-0.6.8.2
- base-orphans-0.7
- bifunctors-5.5.2
- cabal-doctest-1.0.6
- call-stack-0.1.0
- colour-2.3.3
- comonad-5.0.3
- contravariant-1.4.1
- distributive-0.5.3
- exceptions-0.10.0
- fail-4.9.0.0
- free-5.0.1
- generic-deriving-1.12.1
- hashable-1.2.7.0
- kan-extensions-5.1
- lens-4.16.1
- monad-parallel-0.7.2.3
- mtl-2.2.2
- multiset-0.3.3
- parallel-3.2.1.1
- parsec-3.1.13.0
- primitive-0.6.3.0
- profunctors-5.2.2
- reflection-2.1.3
- semigroupoids-5.2.2
- semigroups-0.18.4
- stm-2.4.5.0
- tagged-0.8.5
- text-1.2.3.0
- th-abstraction-0.2.6.0
- transformers-base-0.4.4
- transformers-compat-0.6.0.4
- union-find-array-0.1.0.2
- unordered-containers-0.2.9.0
- vector-0.12.0.1
- void-0.7.2
- ghc-paths-0.1.0.9
- network-2.6.3.4
- random-1.1
- syb-0.7
resolver: ghc-7.10
