flags:
  transformers-compat:
    five-three: true
extra-package-dbs: []
packages:
- .
system-ghc: false
extra-deps:
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-xml
  commit: ac8e4a5920af1e36f09995d03626cfce3d9ee69a
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-ext
  commit: 66f7a9eefbe8335331962bdc5710c8c4392a1188
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-applicative
  commit: b8446e7b4b5403f5122b901d76542eab505cb106
- git: https://github.com/ComputationWithBoundedResources/hoca
  commit: 6f1c5033ee56dcddfeb4947eb9c259fa1e3b07e8
- graphviz-2999.20.0.4
- term-rewriting-0.4.0.2
- union-find-array-0.1.0.2

resolver: lts-16.4
