flags:
  transformers-compat:
    five-three: true
extra-package-dbs: []
packages:
- .
- ../term-rewriting-ext/
- ../term-rewriting-applicative/
- ../hoca/
system-ghc: false
extra-deps:
- graphviz-2999.20.0.4
- term-rewriting-0.4.0.2
- union-find-array-0.1.0.2

resolver: lts-16.1
