flags: {}
extra-package-dbs: []
packages:
- '.'
- ../../term-rewriting-ext/
system-ghc: true
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- base-orphans-0.5.4
- bifunctors-5.3
- comonad-5
- contravariant-1.4
- distributive-0.5.0.2
- exceptions-0.8.2.1
- free-4.12.4
- hashable-1.2.4.0
- kan-extensions-5.0.1
- lens-4.14
- monad-parallel-0.7.2.2
- mtl-2.2.1
- multiset-0.3.3
- parallel-3.2.1.0
- parsec-3.1.11
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- reflection-2.1.2
- semigroupoids-5.0.1
- semigroups-0.18.1
- stm-2.4.4.1
- tagged-0.8.4
- text-1.2.2.1
- transformers-compat-0.5.1.4
- union-find-array-0.1.0.2
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- void-0.7.1
resolver: ghc-8
