type nat = Zero | S of nat;;
type char = SLASH | DOT | MINUS | GT | LPAREN | RPAREN | SPACE | A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z;;


let rec max x y =
  match x with
  | Zero -> y
  | S(x') ->
     match y with
     | Zero -> x
     | S(y') -> S(max x' y')
;;

let not b =
  match b with
  | true -> false
  | false -> true
;;

let eqChar x y =
  match x with
  | A -> (match y with
	  | A -> true
	  | B -> false
	  | C -> false)
  | B -> (match y with
	  | A -> false
	  | B -> true
	  | C -> false)
  | C -> (match y with
	  | A -> false
	  | B -> false
	  | C -> true)
;;
(* let eqChar x y = *)
(*   match x with *)
(*   | SLASH -> (match y with  *)
(*            | SLASH -> true *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | LPAREN -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> true *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | RPAREN -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> true *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | DOT -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> true *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | GT -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> true *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | MINUS -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> true *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | SPACE -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> true *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | A -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> true *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | B -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> true *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | C -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> true *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | D -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> true *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | E -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> true *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | F -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> true *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | G -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> true *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | H -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> true *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | I -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> true *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | J -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> true *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | K -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> true *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | L -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> true *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | M -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> true *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | N -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> true *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | O -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> true *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | P -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> true *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | Q -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> true *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | R -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> true *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | S -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> true *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | T -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> true *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | U -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> true *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | V -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> true *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | W -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> true *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | X -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> true *)
(*            | Y -> false *)
(*            | Z -> false) *)
(*   | Y -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> true *)
(*            | Z -> false) *)
(*   | Z -> (match y with  *)
(*            | SLASH -> false *)
(*            | LPAREN -> false *)
(*            | RPAREN -> false *)
(*            | DOT -> false *)
(*            | GT -> false *)
(*            | MINUS -> false *)
(*            | SPACE -> false *)
(*            | A -> false *)
(*            | B -> false *)
(*            | C -> false *)
(*            | D -> false *)
(*            | E -> false *)
(*            | F -> false *)
(*            | G -> false *)
(*            | H -> false *)
(*            | I -> false *)
(*            | J -> false *)
(*            | K -> false *)
(*            | L -> false *)
(*            | M -> false *)
(*            | N -> false *)
(*            | O -> false *)
(*            | P -> false *)
(*            | Q -> false *)
(*            | R -> false *)
(*            | S -> false *)
(*            | T -> false *)
(*            | U -> false *)
(*            | V -> false *)
(*            | W -> false *)
(*            | X -> false *)
(*            | Y -> false *)
(*            | Z -> true) *)
(* ;; *)

let isAlphaChar x =
  match x with
  | SLASH -> false
  | DOT -> false
  | MINUS -> false
  | GT -> false
  | LPAREN -> false
  | RPAREN -> false
  | SPACE -> false
  | A -> true
  | B -> true
  | C -> true
  | D -> true
  | E -> true
  | F -> true
  | G -> true
  | H -> true
  | I -> true
  | J -> true
  | K -> true
  | L -> true
  | M -> true
  | N -> true
  | O -> true
  | P -> true
  | Q -> true
  | R -> true
  | S -> true
  | T -> true
  | U -> true
  | V -> true
  | W -> true
  | X -> true
  | Y -> true
  | Z -> true
;;

(*
  type 'a parser = 'a SuccCont -> FailCont -> Token list -> Line -> Ans
  type FailCont = Line -> Ans
  type 'a SuccCont = 'a -> FailCont -> Token list -> Line -> Ans

*)

let runParser p str = (force p) (fun a fc tl ln -> ParseSuccess(a,tl)) (fun ln -> ParseFail(ln)) str Zero;;

(* return: 'a -> 'a parser *)
let return x = lazy (fun sc -> sc x) ;;

(* fail : 'a parser *)
let fail = lazy (fun sc fc ts n -> fc n) ;;

(* bind : 'a parser -> ('a -> 'b parser) -> 'b parser *)
let bind p f = lazy (fun sc -> (force p) (fun x -> (force (f x)) sc));;


(* alt : 'a parser -> 'a parser -> 'a parser *)
let alt p q  =
  lazy
    (fun sc fc ts n ->
     let fcp np = (force q) sc (fun nq -> fc (max np nq)) ts n
     in (force p) sc fcp ts n)
;;

(* any : Token parser *)
let any = lazy (fun sc fc ts n ->
		match ts with
		| [] -> fc n
		| t::ts' -> sc t fc ts' S(n))
;;

let eos = lazy (fun sc fc ts n ->
		match ts with
		| [] -> sc Unit fc ts n
		| t::ts' -> fc n)
;;


(* seq : ('a -> 'b -> 'c) -> 'a parser -> 'b parser -> 'c parser *)
let seq f p q = bind p (fun a -> bind q (fun b -> return (f a b)));;

(* bind : 'a parser -> 'b parser -> 'b parser *)
let bind' p q = bind p (fun x -> q);;

(* filter : 'a parser -> ('a -> bool) -> 'a parser *)
let filter p f = bind p (fun x ->
			 match f x with
			 | true -> return x
			 | false -> fail)
;;

(* char : char -> char parser *)
let char c = filter any (eqChar c)
;;

(* char : Char parser *)
let alphaChar = filter any isAlphaChar
;;

let rec string cs =
  match cs with
  | [] -> return Unit
  | c::cs' -> bind' (char c) (string cs')
;;

(* maybe :: 'a parser -> ('a option) parser   *)
let maybe p =
  let someP = bind p (fun r -> return Some(r))
  in alt someP (return None)
;;

let rec many p =
  bind (maybe p)
       (fun ro ->
	match ro with
	| None -> return []
	| Some(r) -> bind (many p) (fun rs -> return r::rs))
;;

let many1 p = seq (fun r rs -> r::rs) p (many p)
;;

let followedBy p q = seq (fun rp rq -> rp) p q
;;
let lexeme p = bind p (fun r -> bind' (alt (char SPACE) (return SPACE)) (return r))
;;

let between pl pr p = bind' pl (bind p (fun r -> bind' pr (return r)))
;;
let parens = between (lexeme (char LPAREN)) (lexeme (char RPAREN))
;;

(* let rec pExp = *)
(*   let pVar = many1 alphaChar *)
(*   and pApp = *)
(*     seq (fun e1 e2 -> App e1 e2) (lexeme pExp) (lexeme pExp) *)
(*   and pAbs = *)
(*     bind' (lexeme (char SLASH)) *)
(* 	  (seq (fun v e -> Abs v e) *)
(* 	       (followedBy (lexeme pVar) (lexeme (char DOT))) *)
(* 	       (lexeme pExp)) *)
(*   in alt pVar (parens (alt pAbs pApp)) *)
(* ;; *)

(* promote : 'a parser parser -> 'a parser *)
let promote p = bind p (fun q -> q)
;;

let parser = bind' (char A) (bind' (char B) eos);;


let main input = runParser parser input;;

